name: Deploy Web

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  flutter-version: 3.10.6

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  verified:
    uses: ./.github/workflows/verify.yml
  deploy:
    needs: verified
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: checkout src
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter-version }}
          channel: 'stable'
      - name: build web
        run: flutter build web
      - name: setup pages
        uses: actions/configure-pages@v3
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/web'
      - name: deploy site
        id: deployment
        uses: actions/deploy-pages@v1
